; Interface-only record. No gameplay/scoring fields are added or repacked.
        rsset 0
U_PREVIOUS_KEYS rs.b 128
U_SAVED_VOLUMES rs.w 3
U_OVERLAY_SIGNATURE rs.w 1
U_WIN_TICKS rs.w 1
U_LAST_GAMES rs.b 2
U_WINNER rs.b 1
U_OVERLAY_KIND rs.b 1
U_IDLE rs.w 1
U_PAGE rs.b 1
U_SELECTION rs.b 1
U_PLAYER_COUNT rs.b 1
U_EDGES rs.b 1
U_DIRTY rs.b 1
U_DEMO_CHOICE rs.b 1 ;0 EXIT (default),1 TAKE OVER
U_DEMO_CURSOR rs.l 1
U_DEMO_REMAINING rs.w 1
U_DEMO_MASK rs.b 1
U_FRESH_INPUT rs.b 1
U_TAKEOVER_EDGE rs.b 1
U_DEMO rs.b 1
U_PAUSED rs.b 1
U_CONFIRMATION rs.b 1
U_KEYBOARD_ENTRY_KEYS rs.b 128
U_JOYSTICK_BITS rs.b 2
U_JOYSTICK_PREVIOUS rs.b 2
U_JOYSTICK_PRESSED rs.b 2
U_JOYSTICK_ENTRY rs.b 2
U_ENTROPY rs.w 1
U_HELP_CHOICE rs.w 1 ; byte0 BACK=0 EXIT=1 NEXT=2; padding preserves alignment
U_SIZE rs.b 0
ui_help_choice equ ui_state+U_HELP_CHOICE
ui_previous_keys equ ui_state+U_PREVIOUS_KEYS
ui_saved_volumes equ ui_state+U_SAVED_VOLUMES
ui_overlay_signature equ ui_state+U_OVERLAY_SIGNATURE
ui_win_ticks equ ui_state+U_WIN_TICKS
ui_last_games equ ui_state+U_LAST_GAMES
ui_winner equ ui_state+U_WINNER
ui_overlay_kind equ ui_state+U_OVERLAY_KIND
ui_idle equ ui_state+U_IDLE
ui_page equ ui_state+U_PAGE
ui_selection equ ui_state+U_SELECTION
ui_player_count equ ui_state+U_PLAYER_COUNT
ui_edges equ ui_state+U_EDGES
ui_dirty equ ui_state+U_DIRTY
ui_demo_choice equ ui_state+U_DEMO_CHOICE
ui_demo_cursor equ ui_state+U_DEMO_CURSOR
ui_demo_remaining equ ui_state+U_DEMO_REMAINING
ui_demo_mask equ ui_state+U_DEMO_MASK
ui_fresh_input equ ui_state+U_FRESH_INPUT
ui_takeover_edge equ ui_state+U_TAKEOVER_EDGE
ui_demo equ ui_state+U_DEMO
ui_paused equ ui_state+U_PAUSED
ui_confirmation equ ui_state+U_CONFIRMATION
ui_keyboard_entry_keys equ ui_state+U_KEYBOARD_ENTRY_KEYS
ui_joystick_bits equ ui_state+U_JOYSTICK_BITS
ui_joystick_previous equ ui_state+U_JOYSTICK_PREVIOUS
ui_joystick_pressed equ ui_state+U_JOYSTICK_PRESSED
ui_joystick_entry equ ui_state+U_JOYSTICK_ENTRY
ui_entropy_state equ ui_state+U_ENTROPY
